version: "3.9"
services:
  db: 
    image: postgres
    volumes: 
      - './tmp/db:/var/lib/postgres/data'
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
  web:
    build: .
    volumes:
      - .:/places-api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    links:
      - "db:database"
    depends_on:
      - db